### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by PrimmaAnna** [LinkinStars/VauntTest#2]
Need a  feature for testing.

**Comment by LinkinStars** [comment]
<a href="https://github.com/LinkinStars/VauntTest" target="_blank">
<p>
  <img src="https://api.vaunt.dev/v1/github/entities/PrimmaAnna/achievements?format=svg&limit=5" width="350" />
</p>
</a>

**Comment by elewis787** [comment]
Here is a link that will show the achievement triggered by this issue https://api.vaunt.dev/v1/github/entities/PrimmaAnna/achievements?limit=4&format=svg
